import { jsPDF } from "jspdf";

export interface QuizReportQuestion {
  question: string;
  options: string[];
  correctAnswer: string;
  userAnswer: string;
  explanation?: string;
}

export interface QuizReportData {
  title: string;
  docName: string;
  dateStr: string;
  totalQuestions: number;
  correctAnswers: number;
  wrongAnswers: number;
  accuracy: number;
  timeTaken: string;
  questions: QuizReportQuestion[];
}

// --- Colour Palette ---
const C = {
  black:    [20,  24,  32]  as [number, number, number],
  slate:    [80,  90, 105]  as [number, number, number],
  muted:    [130, 138, 150] as [number, number, number],
  surface:  [245, 247, 250] as [number, number, number],
  border:   [220, 225, 232] as [number, number, number],
  green:    [22,  163,  74] as [number, number, number],
  greenBg:  [240, 253, 244] as [number, number, number],
  red:      [220,  38,  38] as [number, number, number],
  redBg:    [254, 242, 242] as [number, number, number],
  blue:     [59,  130, 246] as [number, number, number],
  indigo:   [99,  102, 241] as [number, number, number],
  white:    [255, 255, 255] as [number, number, number],
};

export function downloadQuizReport(data: QuizReportData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const PH = doc.internal.pageSize.height;  // 297mm
  const PW = doc.internal.pageSize.width;   // 210mm
  const ML = 18;  // margin left
  const MR = 18;  // margin right
  const TW = PW - ML - MR;  // text width
  const MB = 18;  // margin bottom
  let y = 0;
  let pageNum = 1;

  // -- Helpers --

  const setColor = (rgb: [number, number, number]) =>
    doc.setTextColor(rgb[0], rgb[1], rgb[2]);

  const setFill = (rgb: [number, number, number]) =>
    doc.setFillColor(rgb[0], rgb[1], rgb[2]);

  const setDraw = (rgb: [number, number, number]) =>
    doc.setDrawColor(rgb[0], rgb[1], rgb[2]);

  const font = (style: "normal" | "bold", size: number) => {
    doc.setFont("Helvetica", style);
    doc.setFontSize(size);
  };

  const textLines = (text: string, maxW: number) =>
    doc.splitTextToSize(text, maxW) as string[];

  const lineH = (size: number) => size * 0.3528 * 1.35;  // approx mm per line

  const needsPage = (space: number) => {
    if (y + space > PH - MB - 8) {
      addFooter();
      doc.addPage();
      pageNum++;
      y = 22;
      return true;
    }
    return false;
  };

  // -- Footer --
  const addFooter = () => {
    font("normal", 7.5);
    setColor(C.muted);
    doc.text("Generated by QuizGenerator", ML, PH - 8);
    doc.text(`Page ${pageNum}`, PW - MR - 10, PH - 8, { align: "right" });
    setDraw(C.border);
    doc.setLineWidth(0.2);
    doc.line(ML, PH - 12, PW - MR, PH - 12);
  };

  // -- Cover Banner --
  setFill([30, 35, 50]);
  doc.rect(0, 0, PW, 52, "F");

  // Decorative circle accents
  setFill([255, 255, 255]);
  doc.setGState(new (doc as any).GState({ opacity: 0.04 }));
  doc.circle(PW - 28, 10, 38, "F");
  doc.circle(ML + 8, 52, 22, "F");
  doc.setGState(new (doc as any).GState({ opacity: 1.0 }));

  font("bold", 22);
  setColor(C.white);
  doc.text("Quiz Performance Report", ML, 24);

  font("normal", 9);
  setColor([180, 185, 200] as any);
  doc.text(data.title, ML, 33);

  font("normal", 8);
  setColor([150, 155, 170] as any);
  doc.text(`Source: ${data.docName}`, ML, 40);
  doc.text(`Completed: ${data.dateStr}`, ML, 47);

  y = 60;

  // -- Stats Row --
  const cols = 5;
  const colW = TW / cols;
  const statsY = y;
  const statsH = 22;

  setFill(C.surface);
  setDraw(C.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(ML, statsY, TW, statsH, 3, 3, "FD");

  const statItems = [
    { label: "TOTAL MCQs",  value: String(data.totalQuestions),  color: C.black  },
    { label: "CORRECT",     value: String(data.correctAnswers),   color: C.green  },
    { label: "WRONG",       value: String(data.wrongAnswers),     color: C.red    },
    { label: "ACCURACY",    value: `${data.accuracy}%`,           color: C.indigo },
    { label: "TIME TAKEN",  value: data.timeTaken,                color: C.black  },
  ];

  statItems.forEach((s, i) => {
    const cx = ML + i * colW + colW / 2;
    if (i > 0) {
      setDraw(C.border);
      doc.setLineWidth(0.25);
      doc.line(ML + i * colW, statsY + 4, ML + i * colW, statsY + statsH - 4);
    }
    font("bold", 7);
    setColor(C.muted);
    doc.text(s.label, cx, statsY + 7, { align: "center" });

    font("bold", 11);
    setColor(s.color);
    doc.text(s.value, cx, statsY + 17, { align: "center" });
  });

  y = statsY + statsH + 10;

  // -- Section Heading --
  font("bold", 13);
  setColor(C.black);
  doc.text("Detailed Question Review", ML, y);
  y += 2;
  setDraw(C.border);
  doc.setLineWidth(0.3);
  doc.line(ML, y + 1, PW - MR, y + 1);
  y += 7;

  // -- Questions --
  data.questions.forEach((q, idx) => {
    const isCorrect  = q.userAnswer === q.correctAnswer;
    const unanswered = !q.userAnswer;

    // Estimate total height for this block
    font("bold", 10);
    const qLines = textLines(`${idx + 1}. ${q.question}`, TW - 8);
    let blockH = qLines.length * lineH(10) + 6;

    q.options.forEach((opt) => {
      font("normal", 9);
      const ol = textLines(opt, TW - 18);
      blockH += ol.length * lineH(9) + 2.5;
    });

    blockH += 9; // Correct Answer row
    if (!isCorrect) blockH += 9; // Your Answer row

    if (!isCorrect && q.explanation) {
      font("normal", 8.5);
      const el = textLines(q.explanation, TW - 18);
      blockH += el.length * lineH(8.5) + 12;
    }

    blockH += 8; // padding + gap

    needsPage(blockH);

    // Card Background
    const cardH = blockH - 8;
    const cardColor: [number,number,number] = isCorrect ? C.greenBg : unanswered ? C.surface : C.redBg;
    setFill(cardColor);
    setDraw(isCorrect ? C.green : unanswered ? C.border : C.red);
    doc.setLineWidth(0.25);
    doc.roundedRect(ML, y, TW, cardH, 2.5, 2.5, "FD");

    // Left accent bar
    setFill(isCorrect ? C.green : unanswered ? C.muted : C.red);
    doc.rect(ML, y, 3, cardH, "F");

    const ix = ML + 7;
    const iw = TW - 7;
    y += 6;

    // Question Text
    font("bold", 10);
    setColor(C.black);
    const qWrapped = textLines(`${idx + 1}.  ${q.question}`, iw);
    doc.text(qWrapped, ix, y);
    y += qWrapped.length * lineH(10) + 5;

    // Options 1-4
    q.options.forEach((opt, oi) => {
      // Measure label width while bold, THEN switch font to render value
      font("bold", 9);
      setColor(C.slate);
      const label = `${oi + 1}.`;
      const labelW = doc.getTextWidth(label);
      doc.text(label, ix, y);

      font("normal", 9);
      setColor(C.slate);
      const optLines = textLines(opt, iw - labelW - 5);
      doc.text(optLines, ix + labelW + 3, y);
      y += optLines.length * lineH(9) + 2.5;
    });

    y += 3;

    // Correct Answer row
    // IMPORTANT: measure width in bold BEFORE switching font to normal for value text
    font("bold", 8.5);
    setColor(C.green);
    const correctLabel = "Correct Ans:";
    const correctLabelW = doc.getTextWidth(correctLabel);
    doc.text(correctLabel, ix, y);

    font("normal", 8.5);
    setColor(C.green);
    const correctVal = doc.splitTextToSize(q.correctAnswer, iw - correctLabelW - 5) as string[];
    doc.text(correctVal[0] || "", ix + correctLabelW + 3, y);
    y += 8;

    // Your Answer row (only if wrong or unanswered)
    if (!isCorrect) {
      font("bold", 8.5);
      setColor(C.red);
      const yourLabel = unanswered ? "Your Ans: (Not answered)" : "Your Ans:";
      const yourLabelW = doc.getTextWidth(yourLabel);
      doc.text(yourLabel, ix, y);

      if (!unanswered) {
        font("normal", 8.5);
        setColor(C.red);
        const yourVal = doc.splitTextToSize(q.userAnswer, iw - yourLabelW - 5) as string[];
        doc.text(yourVal[0] || "", ix + yourLabelW + 3, y);
      }
      y += 8;
    }

    // Explanation box (only for wrong/unanswered)
    if (!isCorrect && q.explanation) {
      y += 2;
      font("normal", 8.5);
      setColor(C.slate);

      const expLines = textLines(q.explanation, iw - 10);
      const expH = expLines.length * lineH(8.5) + 7;

      setFill([220, 225, 235] as any);
      setDraw([200, 207, 218] as any);
      doc.setLineWidth(0.2);
      doc.roundedRect(ix, y, iw - 4, expH, 1.5, 1.5, "FD");
      doc.text(expLines, ix + 4, y + 4.5);
      y += expH + 3;
    }

    y += 10; // gap between cards
  });

  // Final Footer
  addFooter();

  // Save
  const safe = data.title.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`quiz_report_${safe}.pdf`);
}
